<?php

/**
 * @file
 * 'Replaces the [tweet https://twitter.com/sillygwailo/status/139116091963211778] shortcode with the embedded code from Twitter
 */

/**
 * Implements hook_filter_info().
 */
function embedded_tweets_filter_info() {
  $filters = array();
  $filters['embedded_tweet'] = array(
    'title' => t('Embedded Tweets Filter'), 
    'description' => t('Replaces the [tweet https://twitter.com/sillygwailo/status/139116091963211778] shortcode with the embedded code from Twitter'),
    'settings callback' => 'embedded_tweets_settings',
    'process callback' => 'embedded_tweets_filter_process',
    'tips callback' => 'embedded_tweets_tips',
  );
  return $filters;
}

/**
 * Filter process callback for Embedded Tweets Filter.
 */
function embedded_tweets_filter_process($text, $filter) {
  if (preg_match_all('/\[tweet((\\s+)(.+))?( .+)?\]/isU', $text, $matches)) {
    $tweet_url = $matches[4][0];
    $tweet_request = file_get_contents("https://api.twitter.com/1/statuses/oembed.json?url=" . urlencode(trim($tweet_url)));
    $tweet = json_decode($tweet_request);
    $replacement = $tweet->html;
/*
    $replacement = 
    '<blockquote class="twitter-tweet"><a href="' . $tweet_url . '">' . $tweet_url . '</a></blockquote>
      <script src="//platform.twitter.com/widgets.js" charset="utf-8"></script>';
*/
    return str_replace($matches[0][0], $replacement, $text);
  }
  return $text;
}

/**
 * Filter tips callback for Embedded Tweets Filter.
 */
function embedded_tweets_tips($delta, $format, $long = FALSE) {
  return t('Replaces the [tweet https://twitter.com/sillygwailo/status/139116091963211778] shortcode with the embedded code from Twitter');
}

/**
 * Filter settings callback for Embedded Tweets Filter.
 */
function embedded_tweets_settings($form, &$form_state, $filter, $format, $defaults) {
  // TODO: alignment settings
  $settings = array();
  return $settings;
}